package com.busterblocks.rental.persistence.table.dto;

import java.math.BigDecimal;
import java.util.Date;

public class LastVideoRentalViewDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_RENTAL_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private BigDecimal VIDEO_RENTAL_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private BigDecimal VIDEO_ITEM_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private BigDecimal CUSTOMER_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_BORROWED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private Date DATE_BORROWED;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_DUE
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private Date DATE_DUE;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_RETURNED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private Date DATE_RETURNED;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.LAST_VIDEO_RENTAL_VIEW.COMMENTS
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    private String COMMENTS;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_RENTAL_ID
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_RENTAL_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public BigDecimal getVIDEO_RENTAL_ID() {
        return VIDEO_RENTAL_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_RENTAL_ID
     *
     * @param VIDEO_RENTAL_ID the value for HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_RENTAL_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setVIDEO_RENTAL_ID(BigDecimal VIDEO_RENTAL_ID) {
        this.VIDEO_RENTAL_ID = VIDEO_RENTAL_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_ITEM_ID
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public BigDecimal getVIDEO_ITEM_ID() {
        return VIDEO_ITEM_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_ITEM_ID
     *
     * @param VIDEO_ITEM_ID the value for HR.LAST_VIDEO_RENTAL_VIEW.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setVIDEO_ITEM_ID(BigDecimal VIDEO_ITEM_ID) {
        this.VIDEO_ITEM_ID = VIDEO_ITEM_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.CUSTOMER_ID
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public BigDecimal getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for HR.LAST_VIDEO_RENTAL_VIEW.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setCUSTOMER_ID(BigDecimal CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_BORROWED
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.DATE_BORROWED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public Date getDATE_BORROWED() {
        return DATE_BORROWED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_BORROWED
     *
     * @param DATE_BORROWED the value for HR.LAST_VIDEO_RENTAL_VIEW.DATE_BORROWED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setDATE_BORROWED(Date DATE_BORROWED) {
        this.DATE_BORROWED = DATE_BORROWED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_DUE
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.DATE_DUE
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public Date getDATE_DUE() {
        return DATE_DUE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_DUE
     *
     * @param DATE_DUE the value for HR.LAST_VIDEO_RENTAL_VIEW.DATE_DUE
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setDATE_DUE(Date DATE_DUE) {
        this.DATE_DUE = DATE_DUE;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_RETURNED
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.DATE_RETURNED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public Date getDATE_RETURNED() {
        return DATE_RETURNED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.DATE_RETURNED
     *
     * @param DATE_RETURNED the value for HR.LAST_VIDEO_RENTAL_VIEW.DATE_RETURNED
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setDATE_RETURNED(Date DATE_RETURNED) {
        this.DATE_RETURNED = DATE_RETURNED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.COMMENTS
     *
     * @return the value of HR.LAST_VIDEO_RENTAL_VIEW.COMMENTS
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public String getCOMMENTS() {
        return COMMENTS;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.LAST_VIDEO_RENTAL_VIEW.COMMENTS
     *
     * @param COMMENTS the value for HR.LAST_VIDEO_RENTAL_VIEW.COMMENTS
     *
     * @ibatorgenerated Mon Jun 15 18:56:37 CAT 2015
     */
    public void setCOMMENTS(String COMMENTS) {
        this.COMMENTS = COMMENTS == null ? null : COMMENTS.trim();
    }
}