package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.ActorDto;
import com.busterblocks.video.persistence.table.dto.ActorDtoExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ActorDtoDAOImpl extends SqlMapClientDaoSupport implements ActorDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public ActorDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int countByExample(ActorDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_ACTOR.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByExample(ActorDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_ACTOR.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByPrimaryKey(BigDecimal ACTOR_ID) {
        ActorDto key = new ActorDto();
        key.setACTOR_ID(ACTOR_ID);
        int rows = getSqlMapClientTemplate().delete("HR_ACTOR.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insert(ActorDto record) {
        getSqlMapClientTemplate().insert("HR_ACTOR.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insertSelective(ActorDto record) {
        getSqlMapClientTemplate().insert("HR_ACTOR.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<ActorDto> selectByExample(ActorDtoExample example) {
        List<ActorDto> list = getSqlMapClientTemplate().queryForList("HR_ACTOR.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public ActorDto selectByPrimaryKey(BigDecimal ACTOR_ID) {
        ActorDto key = new ActorDto();
        key.setACTOR_ID(ACTOR_ID);
        ActorDto record = (ActorDto) getSqlMapClientTemplate().queryForObject("HR_ACTOR.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExampleSelective(ActorDto record, ActorDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_ACTOR.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExample(ActorDto record, ActorDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_ACTOR.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKeySelective(ActorDto record) {
        int rows = getSqlMapClientTemplate().update("HR_ACTOR.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKey(ActorDto record) {
        int rows = getSqlMapClientTemplate().update("HR_ACTOR.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private static class UpdateByExampleParms extends ActorDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, ActorDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}