package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.GenreDto;
import com.busterblocks.video.persistence.table.dto.GenreDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface GenreDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int countByExample(GenreDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByExample(GenreDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal GENRE_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insert(GenreDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insertSelective(GenreDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    List<GenreDto> selectByExample(GenreDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    GenreDto selectByPrimaryKey(BigDecimal GENRE_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExampleSelective(GenreDto record, GenreDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExample(GenreDto record, GenreDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKeySelective(GenreDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.GENRE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKey(GenreDto record);
}