package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.MovieActorDtoExample;
import com.busterblocks.video.persistence.table.dto.MovieActorDtoKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MovieActorDtoDAOImpl extends SqlMapClientDaoSupport implements MovieActorDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public MovieActorDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int countByExample(MovieActorDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_MOVIE_ACTOR.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByExample(MovieActorDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_MOVIE_ACTOR.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByPrimaryKey(MovieActorDtoKey key) {
        int rows = getSqlMapClientTemplate().delete("HR_MOVIE_ACTOR.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insert(MovieActorDtoKey record) {
        getSqlMapClientTemplate().insert("HR_MOVIE_ACTOR.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insertSelective(MovieActorDtoKey record) {
        getSqlMapClientTemplate().insert("HR_MOVIE_ACTOR.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<MovieActorDtoKey> selectByExample(MovieActorDtoExample example) {
        List<MovieActorDtoKey> list = getSqlMapClientTemplate().queryForList("HR_MOVIE_ACTOR.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExampleSelective(MovieActorDtoKey record, MovieActorDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_MOVIE_ACTOR.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExample(MovieActorDtoKey record, MovieActorDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_MOVIE_ACTOR.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.MOVIE_ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private static class UpdateByExampleParms extends MovieActorDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, MovieActorDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}