package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.MovieDto;
import com.busterblocks.video.persistence.table.dto.MovieDtoExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MovieDtoDAOImpl extends SqlMapClientDaoSupport implements MovieDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public MovieDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int countByExample(MovieDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_MOVIE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByExample(MovieDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_MOVIE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByPrimaryKey(BigDecimal MOVIE_ID) {
        MovieDto key = new MovieDto();
        key.setMOVIE_ID(MOVIE_ID);
        int rows = getSqlMapClientTemplate().delete("HR_MOVIE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insert(MovieDto record) {
        getSqlMapClientTemplate().insert("HR_MOVIE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insertSelective(MovieDto record) {
        getSqlMapClientTemplate().insert("HR_MOVIE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<MovieDto> selectByExample(MovieDtoExample example) {
        List<MovieDto> list = getSqlMapClientTemplate().queryForList("HR_MOVIE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public MovieDto selectByPrimaryKey(BigDecimal MOVIE_ID) {
        MovieDto key = new MovieDto();
        key.setMOVIE_ID(MOVIE_ID);
        MovieDto record = (MovieDto) getSqlMapClientTemplate().queryForObject("HR_MOVIE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExampleSelective(MovieDto record, MovieDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_MOVIE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExample(MovieDto record, MovieDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_MOVIE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKeySelective(MovieDto record) {
        int rows = getSqlMapClientTemplate().update("HR_MOVIE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKey(MovieDto record) {
        int rows = getSqlMapClientTemplate().update("HR_MOVIE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.MOVIE
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private static class UpdateByExampleParms extends MovieDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, MovieDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}