package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoItemDto;
import com.busterblocks.video.persistence.table.dto.VideoItemDtoExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VideoItemDtoDAOImpl extends SqlMapClientDaoSupport implements VideoItemDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public VideoItemDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int countByExample(VideoItemDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_VIDEO_ITEM.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int deleteByExample(VideoItemDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_VIDEO_ITEM.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int deleteByPrimaryKey(BigDecimal VIDEO_ITEM_ID) {
        VideoItemDto key = new VideoItemDto();
        key.setVIDEO_ITEM_ID(VIDEO_ITEM_ID);
        int rows = getSqlMapClientTemplate().delete("HR_VIDEO_ITEM.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void insert(VideoItemDto record) {
        getSqlMapClientTemplate().insert("HR_VIDEO_ITEM.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void insertSelective(VideoItemDto record) {
        getSqlMapClientTemplate().insert("HR_VIDEO_ITEM.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<VideoItemDto> selectByExample(VideoItemDtoExample example) {
        List<VideoItemDto> list = getSqlMapClientTemplate().queryForList("HR_VIDEO_ITEM.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public VideoItemDto selectByPrimaryKey(BigDecimal VIDEO_ITEM_ID) {
        VideoItemDto key = new VideoItemDto();
        key.setVIDEO_ITEM_ID(VIDEO_ITEM_ID);
        VideoItemDto record = (VideoItemDto) getSqlMapClientTemplate().queryForObject("HR_VIDEO_ITEM.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int updateByExampleSelective(VideoItemDto record, VideoItemDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_ITEM.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int updateByExample(VideoItemDto record, VideoItemDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_ITEM.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int updateByPrimaryKeySelective(VideoItemDto record) {
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_ITEM.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public int updateByPrimaryKey(VideoItemDto record) {
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_ITEM.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private static class UpdateByExampleParms extends VideoItemDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoItemDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}