package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoStatusDto;
import com.busterblocks.video.persistence.table.dto.VideoStatusDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface VideoStatusDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int countByExample(VideoStatusDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int deleteByExample(VideoStatusDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal VIDEO_STATUS_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    void insert(VideoStatusDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    void insertSelective(VideoStatusDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    List<VideoStatusDto> selectByExample(VideoStatusDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    VideoStatusDto selectByPrimaryKey(BigDecimal VIDEO_STATUS_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByExampleSelective(VideoStatusDto record, VideoStatusDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByExample(VideoStatusDto record, VideoStatusDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByPrimaryKeySelective(VideoStatusDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_STATUS
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByPrimaryKey(VideoStatusDto record);
}