package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoDto;
import com.busterblocks.video.persistence.table.dto.VideoDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface VideoDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int countByExample(VideoDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByExample(VideoDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal VIDEO_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insert(VideoDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insertSelective(VideoDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    List<VideoDto> selectByExample(VideoDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    VideoDto selectByPrimaryKey(BigDecimal VIDEO_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExampleSelective(VideoDto record, VideoDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExample(VideoDto record, VideoDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKeySelective(VideoDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKey(VideoDto record);
}