package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoItemDto;
import com.busterblocks.video.persistence.table.dto.VideoItemDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface VideoItemDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int countByExample(VideoItemDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int deleteByExample(VideoItemDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal VIDEO_ITEM_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    void insert(VideoItemDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    void insertSelective(VideoItemDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    List<VideoItemDto> selectByExample(VideoItemDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    VideoItemDto selectByPrimaryKey(BigDecimal VIDEO_ITEM_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByExampleSelective(VideoItemDto record, VideoItemDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByExample(VideoItemDto record, VideoItemDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByPrimaryKeySelective(VideoItemDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    int updateByPrimaryKey(VideoItemDto record);
}