package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoViewDto;
import com.busterblocks.video.persistence.table.dto.VideoViewDtoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VideoViewDtoDAOImpl extends SqlMapClientDaoSupport implements VideoViewDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public VideoViewDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public int countByExample(VideoViewDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_VIDEO_VIEW.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public int deleteByExample(VideoViewDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_VIDEO_VIEW.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public void insert(VideoViewDto record) {
        getSqlMapClientTemplate().insert("HR_VIDEO_VIEW.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public void insertSelective(VideoViewDto record) {
        getSqlMapClientTemplate().insert("HR_VIDEO_VIEW.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<VideoViewDto> selectByExample(VideoViewDtoExample example) {
        List<VideoViewDto> list = getSqlMapClientTemplate().queryForList("HR_VIDEO_VIEW.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public int updateByExampleSelective(VideoViewDto record, VideoViewDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_VIEW.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public int updateByExample(VideoViewDto record, VideoViewDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_VIDEO_VIEW.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    private static class UpdateByExampleParms extends VideoViewDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, VideoViewDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}