package com.busterblocks.video.persistence.table.dao;

import com.busterblocks.video.persistence.table.dto.VideoViewDto;
import com.busterblocks.video.persistence.table.dto.VideoViewDtoExample;
import java.util.List;

public interface VideoViewDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    int countByExample(VideoViewDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    int deleteByExample(VideoViewDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    void insert(VideoViewDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    void insertSelective(VideoViewDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    List<VideoViewDto> selectByExample(VideoViewDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    int updateByExampleSelective(VideoViewDto record, VideoViewDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    int updateByExample(VideoViewDto record, VideoViewDtoExample example);
}