package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ActorDtoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public ActorDtoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected ActorDtoExample(ActorDtoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.ACTOR
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andACTOR_IDIsNull() {
            addCriterion("ACTOR_ID is null");
            return this;
        }

        public Criteria andACTOR_IDIsNotNull() {
            addCriterion("ACTOR_ID is not null");
            return this;
        }

        public Criteria andACTOR_IDEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID =", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID <>", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDGreaterThan(BigDecimal value) {
            addCriterion("ACTOR_ID >", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID >=", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDLessThan(BigDecimal value) {
            addCriterion("ACTOR_ID <", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID <=", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDIn(List<BigDecimal> values) {
            addCriterion("ACTOR_ID in", values, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotIn(List<BigDecimal> values) {
            addCriterion("ACTOR_ID not in", values, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTOR_ID between", value1, value2, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTOR_ID not between", value1, value2, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_NAMEIsNull() {
            addCriterion("ACTOR_NAME is null");
            return this;
        }

        public Criteria andACTOR_NAMEIsNotNull() {
            addCriterion("ACTOR_NAME is not null");
            return this;
        }

        public Criteria andACTOR_NAMEEqualTo(String value) {
            addCriterion("ACTOR_NAME =", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotEqualTo(String value) {
            addCriterion("ACTOR_NAME <>", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEGreaterThan(String value) {
            addCriterion("ACTOR_NAME >", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ACTOR_NAME >=", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELessThan(String value) {
            addCriterion("ACTOR_NAME <", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELessThanOrEqualTo(String value) {
            addCriterion("ACTOR_NAME <=", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELike(String value) {
            addCriterion("ACTOR_NAME like", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotLike(String value) {
            addCriterion("ACTOR_NAME not like", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEIn(List<String> values) {
            addCriterion("ACTOR_NAME in", values, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotIn(List<String> values) {
            addCriterion("ACTOR_NAME not in", values, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEBetween(String value1, String value2) {
            addCriterion("ACTOR_NAME between", value1, value2, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotBetween(String value1, String value2) {
            addCriterion("ACTOR_NAME not between", value1, value2, "ACTOR_NAME");
            return this;
        }
    }
}