package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;

public class ActorDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal ACTOR_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.ACTOR.ACTOR_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String ACTOR_NAME;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.ACTOR.ACTOR_ID
     *
     * @return the value of HR.ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getACTOR_ID() {
        return ACTOR_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.ACTOR.ACTOR_ID
     *
     * @param ACTOR_ID the value for HR.ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setACTOR_ID(BigDecimal ACTOR_ID) {
        this.ACTOR_ID = ACTOR_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.ACTOR.ACTOR_NAME
     *
     * @return the value of HR.ACTOR.ACTOR_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getACTOR_NAME() {
        return ACTOR_NAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.ACTOR.ACTOR_NAME
     *
     * @param ACTOR_NAME the value for HR.ACTOR.ACTOR_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setACTOR_NAME(String ACTOR_NAME) {
        this.ACTOR_NAME = ACTOR_NAME == null ? null : ACTOR_NAME.trim();
    }
}