package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;

public class GenreDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.GENRE.GENRE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal GENRE_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.GENRE.DESCRIPTION
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String DESCRIPTION;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.GENRE.GENRE_ID
     *
     * @return the value of HR.GENRE.GENRE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getGENRE_ID() {
        return GENRE_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.GENRE.GENRE_ID
     *
     * @param GENRE_ID the value for HR.GENRE.GENRE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setGENRE_ID(BigDecimal GENRE_ID) {
        this.GENRE_ID = GENRE_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.GENRE.DESCRIPTION
     *
     * @return the value of HR.GENRE.DESCRIPTION
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.GENRE.DESCRIPTION
     *
     * @param DESCRIPTION the value for HR.GENRE.DESCRIPTION
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }
}