package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;

public class MovieActorDtoKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.MOVIE_ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal ACTOR_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.MOVIE_ACTOR.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal MOVIE_ID;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.MOVIE_ACTOR.ACTOR_ID
     *
     * @return the value of HR.MOVIE_ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getACTOR_ID() {
        return ACTOR_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.MOVIE_ACTOR.ACTOR_ID
     *
     * @param ACTOR_ID the value for HR.MOVIE_ACTOR.ACTOR_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setACTOR_ID(BigDecimal ACTOR_ID) {
        this.ACTOR_ID = ACTOR_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.MOVIE_ACTOR.MOVIE_ID
     *
     * @return the value of HR.MOVIE_ACTOR.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getMOVIE_ID() {
        return MOVIE_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.MOVIE_ACTOR.MOVIE_ID
     *
     * @param MOVIE_ID the value for HR.MOVIE_ACTOR.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setMOVIE_ID(BigDecimal MOVIE_ID) {
        this.MOVIE_ID = MOVIE_ID;
    }
}