package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;
import java.util.Date;

public class VideoDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal VIDEO_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal MOVIE_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO.DATE_RELEASED
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private Date DATE_RELEASED;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO.VIDEO_ID
     *
     * @return the value of HR.VIDEO.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getVIDEO_ID() {
        return VIDEO_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO.VIDEO_ID
     *
     * @param VIDEO_ID the value for HR.VIDEO.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setVIDEO_ID(BigDecimal VIDEO_ID) {
        this.VIDEO_ID = VIDEO_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO.MOVIE_ID
     *
     * @return the value of HR.VIDEO.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getMOVIE_ID() {
        return MOVIE_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO.MOVIE_ID
     *
     * @param MOVIE_ID the value for HR.VIDEO.MOVIE_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setMOVIE_ID(BigDecimal MOVIE_ID) {
        this.MOVIE_ID = MOVIE_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO.DATE_RELEASED
     *
     * @return the value of HR.VIDEO.DATE_RELEASED
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public Date getDATE_RELEASED() {
        return DATE_RELEASED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO.DATE_RELEASED
     *
     * @param DATE_RELEASED the value for HR.VIDEO.DATE_RELEASED
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setDATE_RELEASED(Date DATE_RELEASED) {
        this.DATE_RELEASED = DATE_RELEASED;
    }
}