package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;
import java.util.Date;

public class VideoItemDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO_ITEM.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private BigDecimal VIDEO_ITEM_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO_ITEM.SERIAL_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private String SERIAL_NUMBER;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO_ITEM.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private BigDecimal VIDEO_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO_ITEM.DATE_CREATED
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private Date DATE_CREATED;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.VIDEO_ITEM.VIDEO_STATUS_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    private BigDecimal VIDEO_STATUS_ID;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO_ITEM.VIDEO_ITEM_ID
     *
     * @return the value of HR.VIDEO_ITEM.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public BigDecimal getVIDEO_ITEM_ID() {
        return VIDEO_ITEM_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO_ITEM.VIDEO_ITEM_ID
     *
     * @param VIDEO_ITEM_ID the value for HR.VIDEO_ITEM.VIDEO_ITEM_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setVIDEO_ITEM_ID(BigDecimal VIDEO_ITEM_ID) {
        this.VIDEO_ITEM_ID = VIDEO_ITEM_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO_ITEM.SERIAL_NUMBER
     *
     * @return the value of HR.VIDEO_ITEM.SERIAL_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public String getSERIAL_NUMBER() {
        return SERIAL_NUMBER;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO_ITEM.SERIAL_NUMBER
     *
     * @param SERIAL_NUMBER the value for HR.VIDEO_ITEM.SERIAL_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setSERIAL_NUMBER(String SERIAL_NUMBER) {
        this.SERIAL_NUMBER = SERIAL_NUMBER == null ? null : SERIAL_NUMBER.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO_ITEM.VIDEO_ID
     *
     * @return the value of HR.VIDEO_ITEM.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public BigDecimal getVIDEO_ID() {
        return VIDEO_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO_ITEM.VIDEO_ID
     *
     * @param VIDEO_ID the value for HR.VIDEO_ITEM.VIDEO_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setVIDEO_ID(BigDecimal VIDEO_ID) {
        this.VIDEO_ID = VIDEO_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO_ITEM.DATE_CREATED
     *
     * @return the value of HR.VIDEO_ITEM.DATE_CREATED
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public Date getDATE_CREATED() {
        return DATE_CREATED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO_ITEM.DATE_CREATED
     *
     * @param DATE_CREATED the value for HR.VIDEO_ITEM.DATE_CREATED
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setDATE_CREATED(Date DATE_CREATED) {
        this.DATE_CREATED = DATE_CREATED;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.VIDEO_ITEM.VIDEO_STATUS_ID
     *
     * @return the value of HR.VIDEO_ITEM.VIDEO_STATUS_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public BigDecimal getVIDEO_STATUS_ID() {
        return VIDEO_STATUS_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.VIDEO_ITEM.VIDEO_STATUS_ID
     *
     * @param VIDEO_STATUS_ID the value for HR.VIDEO_ITEM.VIDEO_STATUS_ID
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setVIDEO_STATUS_ID(BigDecimal VIDEO_STATUS_ID) {
        this.VIDEO_STATUS_ID = VIDEO_STATUS_ID;
    }
}