package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class VideoViewDtoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public VideoViewDtoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    protected VideoViewDtoExample(VideoViewDtoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.VIDEO_VIEW
     *
     * @ibatorgenerated Mon Jun 15 18:30:59 CAT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andMOVIE_IDIsNull() {
            addCriterion("MOVIE_ID is null");
            return this;
        }

        public Criteria andMOVIE_IDIsNotNull() {
            addCriterion("MOVIE_ID is not null");
            return this;
        }

        public Criteria andMOVIE_IDEqualTo(BigDecimal value) {
            addCriterion("MOVIE_ID =", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDNotEqualTo(BigDecimal value) {
            addCriterion("MOVIE_ID <>", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDGreaterThan(BigDecimal value) {
            addCriterion("MOVIE_ID >", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MOVIE_ID >=", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDLessThan(BigDecimal value) {
            addCriterion("MOVIE_ID <", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MOVIE_ID <=", value, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDIn(List<BigDecimal> values) {
            addCriterion("MOVIE_ID in", values, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDNotIn(List<BigDecimal> values) {
            addCriterion("MOVIE_ID not in", values, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOVIE_ID between", value1, value2, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MOVIE_ID not between", value1, value2, "MOVIE_ID");
            return this;
        }

        public Criteria andMOVIE_NAMEIsNull() {
            addCriterion("MOVIE_NAME is null");
            return this;
        }

        public Criteria andMOVIE_NAMEIsNotNull() {
            addCriterion("MOVIE_NAME is not null");
            return this;
        }

        public Criteria andMOVIE_NAMEEqualTo(String value) {
            addCriterion("MOVIE_NAME =", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMENotEqualTo(String value) {
            addCriterion("MOVIE_NAME <>", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMEGreaterThan(String value) {
            addCriterion("MOVIE_NAME >", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("MOVIE_NAME >=", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMELessThan(String value) {
            addCriterion("MOVIE_NAME <", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMELessThanOrEqualTo(String value) {
            addCriterion("MOVIE_NAME <=", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMELike(String value) {
            addCriterion("MOVIE_NAME like", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMENotLike(String value) {
            addCriterion("MOVIE_NAME not like", value, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMEIn(List<String> values) {
            addCriterion("MOVIE_NAME in", values, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMENotIn(List<String> values) {
            addCriterion("MOVIE_NAME not in", values, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMEBetween(String value1, String value2) {
            addCriterion("MOVIE_NAME between", value1, value2, "MOVIE_NAME");
            return this;
        }

        public Criteria andMOVIE_NAMENotBetween(String value1, String value2) {
            addCriterion("MOVIE_NAME not between", value1, value2, "MOVIE_NAME");
            return this;
        }

        public Criteria andGENRE_IDIsNull() {
            addCriterion("GENRE_ID is null");
            return this;
        }

        public Criteria andGENRE_IDIsNotNull() {
            addCriterion("GENRE_ID is not null");
            return this;
        }

        public Criteria andGENRE_IDEqualTo(BigDecimal value) {
            addCriterion("GENRE_ID =", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDNotEqualTo(BigDecimal value) {
            addCriterion("GENRE_ID <>", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDGreaterThan(BigDecimal value) {
            addCriterion("GENRE_ID >", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GENRE_ID >=", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDLessThan(BigDecimal value) {
            addCriterion("GENRE_ID <", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GENRE_ID <=", value, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDIn(List<BigDecimal> values) {
            addCriterion("GENRE_ID in", values, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDNotIn(List<BigDecimal> values) {
            addCriterion("GENRE_ID not in", values, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GENRE_ID between", value1, value2, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GENRE_ID not between", value1, value2, "GENRE_ID");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONIsNull() {
            addCriterion("GENRE_DESCRIPTION is null");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONIsNotNull() {
            addCriterion("GENRE_DESCRIPTION is not null");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONEqualTo(String value) {
            addCriterion("GENRE_DESCRIPTION =", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONNotEqualTo(String value) {
            addCriterion("GENRE_DESCRIPTION <>", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONGreaterThan(String value) {
            addCriterion("GENRE_DESCRIPTION >", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("GENRE_DESCRIPTION >=", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONLessThan(String value) {
            addCriterion("GENRE_DESCRIPTION <", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("GENRE_DESCRIPTION <=", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONLike(String value) {
            addCriterion("GENRE_DESCRIPTION like", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONNotLike(String value) {
            addCriterion("GENRE_DESCRIPTION not like", value, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONIn(List<String> values) {
            addCriterion("GENRE_DESCRIPTION in", values, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONNotIn(List<String> values) {
            addCriterion("GENRE_DESCRIPTION not in", values, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONBetween(String value1, String value2) {
            addCriterion("GENRE_DESCRIPTION between", value1, value2, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andGENRE_DESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("GENRE_DESCRIPTION not between", value1, value2, "GENRE_DESCRIPTION");
            return this;
        }

        public Criteria andACTOR_IDIsNull() {
            addCriterion("ACTOR_ID is null");
            return this;
        }

        public Criteria andACTOR_IDIsNotNull() {
            addCriterion("ACTOR_ID is not null");
            return this;
        }

        public Criteria andACTOR_IDEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID =", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID <>", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDGreaterThan(BigDecimal value) {
            addCriterion("ACTOR_ID >", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID >=", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDLessThan(BigDecimal value) {
            addCriterion("ACTOR_ID <", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTOR_ID <=", value, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDIn(List<BigDecimal> values) {
            addCriterion("ACTOR_ID in", values, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotIn(List<BigDecimal> values) {
            addCriterion("ACTOR_ID not in", values, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTOR_ID between", value1, value2, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTOR_ID not between", value1, value2, "ACTOR_ID");
            return this;
        }

        public Criteria andACTOR_NAMEIsNull() {
            addCriterion("ACTOR_NAME is null");
            return this;
        }

        public Criteria andACTOR_NAMEIsNotNull() {
            addCriterion("ACTOR_NAME is not null");
            return this;
        }

        public Criteria andACTOR_NAMEEqualTo(String value) {
            addCriterion("ACTOR_NAME =", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotEqualTo(String value) {
            addCriterion("ACTOR_NAME <>", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEGreaterThan(String value) {
            addCriterion("ACTOR_NAME >", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("ACTOR_NAME >=", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELessThan(String value) {
            addCriterion("ACTOR_NAME <", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELessThanOrEqualTo(String value) {
            addCriterion("ACTOR_NAME <=", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMELike(String value) {
            addCriterion("ACTOR_NAME like", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotLike(String value) {
            addCriterion("ACTOR_NAME not like", value, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEIn(List<String> values) {
            addCriterion("ACTOR_NAME in", values, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotIn(List<String> values) {
            addCriterion("ACTOR_NAME not in", values, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMEBetween(String value1, String value2) {
            addCriterion("ACTOR_NAME between", value1, value2, "ACTOR_NAME");
            return this;
        }

        public Criteria andACTOR_NAMENotBetween(String value1, String value2) {
            addCriterion("ACTOR_NAME not between", value1, value2, "ACTOR_NAME");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESIsNull() {
            addCriterion("DURATION_IN_MINUTES is null");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESIsNotNull() {
            addCriterion("DURATION_IN_MINUTES is not null");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESEqualTo(Short value) {
            addCriterion("DURATION_IN_MINUTES =", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESNotEqualTo(Short value) {
            addCriterion("DURATION_IN_MINUTES <>", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESGreaterThan(Short value) {
            addCriterion("DURATION_IN_MINUTES >", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESGreaterThanOrEqualTo(Short value) {
            addCriterion("DURATION_IN_MINUTES >=", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESLessThan(Short value) {
            addCriterion("DURATION_IN_MINUTES <", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESLessThanOrEqualTo(Short value) {
            addCriterion("DURATION_IN_MINUTES <=", value, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESIn(List<Short> values) {
            addCriterion("DURATION_IN_MINUTES in", values, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESNotIn(List<Short> values) {
            addCriterion("DURATION_IN_MINUTES not in", values, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESBetween(Short value1, Short value2) {
            addCriterion("DURATION_IN_MINUTES between", value1, value2, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andDURATION_IN_MINUTESNotBetween(Short value1, Short value2) {
            addCriterion("DURATION_IN_MINUTES not between", value1, value2, "DURATION_IN_MINUTES");
            return this;
        }

        public Criteria andVIDEO_IDIsNull() {
            addCriterion("VIDEO_ID is null");
            return this;
        }

        public Criteria andVIDEO_IDIsNotNull() {
            addCriterion("VIDEO_ID is not null");
            return this;
        }

        public Criteria andVIDEO_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID =", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID <>", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_ID >", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID >=", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_ID <", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID <=", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ID in", values, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ID not in", values, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ID between", value1, value2, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ID not between", value1, value2, "VIDEO_ID");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDIsNull() {
            addCriterion("DATE_VIDEO_RELEASED is null");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDIsNotNull() {
            addCriterion("DATE_VIDEO_RELEASED is not null");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED =", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDNotEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED <>", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDGreaterThan(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED >", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED >=", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDLessThan(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED <", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED <=", value, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED in", values, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDNotIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED not in", values, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED between", value1, value2, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andDATE_VIDEO_RELEASEDNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_VIDEO_RELEASED not between", value1, value2, "DATE_VIDEO_RELEASED");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDIsNull() {
            addCriterion("VIDEO_ITEM_ID is null");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDIsNotNull() {
            addCriterion("VIDEO_ITEM_ID is not null");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID =", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <>", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID >", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID >=", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <=", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ITEM_ID in", values, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ITEM_ID not in", values, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ITEM_ID between", value1, value2, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ITEM_ID not between", value1, value2, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andSERIAL_NUMBERIsNull() {
            addCriterion("SERIAL_NUMBER is null");
            return this;
        }

        public Criteria andSERIAL_NUMBERIsNotNull() {
            addCriterion("SERIAL_NUMBER is not null");
            return this;
        }

        public Criteria andSERIAL_NUMBEREqualTo(String value) {
            addCriterion("SERIAL_NUMBER =", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotEqualTo(String value) {
            addCriterion("SERIAL_NUMBER <>", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERGreaterThan(String value) {
            addCriterion("SERIAL_NUMBER >", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL_NUMBER >=", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLessThan(String value) {
            addCriterion("SERIAL_NUMBER <", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("SERIAL_NUMBER <=", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLike(String value) {
            addCriterion("SERIAL_NUMBER like", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotLike(String value) {
            addCriterion("SERIAL_NUMBER not like", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERIn(List<String> values) {
            addCriterion("SERIAL_NUMBER in", values, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotIn(List<String> values) {
            addCriterion("SERIAL_NUMBER not in", values, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERBetween(String value1, String value2) {
            addCriterion("SERIAL_NUMBER between", value1, value2, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotBetween(String value1, String value2) {
            addCriterion("SERIAL_NUMBER not between", value1, value2, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDIsNull() {
            addCriterion("DATE_VIDEO_ITEM_CREATED is null");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDIsNotNull() {
            addCriterion("DATE_VIDEO_ITEM_CREATED is not null");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED =", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDNotEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED <>", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDGreaterThan(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED >", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED >=", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDLessThan(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED <", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED <=", value, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED in", values, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDNotIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED not in", values, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED between", value1, value2, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andDATE_VIDEO_ITEM_CREATEDNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_VIDEO_ITEM_CREATED not between", value1, value2, "DATE_VIDEO_ITEM_CREATED");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIsNull() {
            addCriterion("VIDEO_STATUS_ID is null");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIsNotNull() {
            addCriterion("VIDEO_STATUS_ID is not null");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID =", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <>", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID >", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID >=", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <=", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_STATUS_ID in", values, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_STATUS_ID not in", values, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_STATUS_ID between", value1, value2, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_STATUS_ID not between", value1, value2, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONIsNull() {
            addCriterion("VIDEO_STATUS_DESCRIPTION is null");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONIsNotNull() {
            addCriterion("VIDEO_STATUS_DESCRIPTION is not null");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONEqualTo(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION =", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONNotEqualTo(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION <>", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONGreaterThan(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION >", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION >=", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONLessThan(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION <", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION <=", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONLike(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION like", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONNotLike(String value) {
            addCriterion("VIDEO_STATUS_DESCRIPTION not like", value, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONIn(List<String> values) {
            addCriterion("VIDEO_STATUS_DESCRIPTION in", values, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONNotIn(List<String> values) {
            addCriterion("VIDEO_STATUS_DESCRIPTION not in", values, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONBetween(String value1, String value2) {
            addCriterion("VIDEO_STATUS_DESCRIPTION between", value1, value2, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }

        public Criteria andVIDEO_STATUS_DESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("VIDEO_STATUS_DESCRIPTION not between", value1, value2, "VIDEO_STATUS_DESCRIPTION");
            return this;
        }
    }
}