package com.busterblocks.video.persistence.table.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class VideoItemDtoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public VideoItemDtoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    protected VideoItemDtoExample(VideoItemDtoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.VIDEO_ITEM
     *
     * @ibatorgenerated Mon Jun 15 18:24:55 CAT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andVIDEO_ITEM_IDIsNull() {
            addCriterion("VIDEO_ITEM_ID is null");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDIsNotNull() {
            addCriterion("VIDEO_ITEM_ID is not null");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID =", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <>", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID >", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID >=", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ITEM_ID <=", value, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ITEM_ID in", values, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ITEM_ID not in", values, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ITEM_ID between", value1, value2, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andVIDEO_ITEM_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ITEM_ID not between", value1, value2, "VIDEO_ITEM_ID");
            return this;
        }

        public Criteria andSERIAL_NUMBERIsNull() {
            addCriterion("SERIAL_NUMBER is null");
            return this;
        }

        public Criteria andSERIAL_NUMBERIsNotNull() {
            addCriterion("SERIAL_NUMBER is not null");
            return this;
        }

        public Criteria andSERIAL_NUMBEREqualTo(String value) {
            addCriterion("SERIAL_NUMBER =", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotEqualTo(String value) {
            addCriterion("SERIAL_NUMBER <>", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERGreaterThan(String value) {
            addCriterion("SERIAL_NUMBER >", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL_NUMBER >=", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLessThan(String value) {
            addCriterion("SERIAL_NUMBER <", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("SERIAL_NUMBER <=", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERLike(String value) {
            addCriterion("SERIAL_NUMBER like", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotLike(String value) {
            addCriterion("SERIAL_NUMBER not like", value, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERIn(List<String> values) {
            addCriterion("SERIAL_NUMBER in", values, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotIn(List<String> values) {
            addCriterion("SERIAL_NUMBER not in", values, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERBetween(String value1, String value2) {
            addCriterion("SERIAL_NUMBER between", value1, value2, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andSERIAL_NUMBERNotBetween(String value1, String value2) {
            addCriterion("SERIAL_NUMBER not between", value1, value2, "SERIAL_NUMBER");
            return this;
        }

        public Criteria andVIDEO_IDIsNull() {
            addCriterion("VIDEO_ID is null");
            return this;
        }

        public Criteria andVIDEO_IDIsNotNull() {
            addCriterion("VIDEO_ID is not null");
            return this;
        }

        public Criteria andVIDEO_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID =", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID <>", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_ID >", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID >=", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_ID <", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_ID <=", value, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ID in", values, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_ID not in", values, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ID between", value1, value2, "VIDEO_ID");
            return this;
        }

        public Criteria andVIDEO_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_ID not between", value1, value2, "VIDEO_ID");
            return this;
        }

        public Criteria andDATE_CREATEDIsNull() {
            addCriterion("DATE_CREATED is null");
            return this;
        }

        public Criteria andDATE_CREATEDIsNotNull() {
            addCriterion("DATE_CREATED is not null");
            return this;
        }

        public Criteria andDATE_CREATEDEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_CREATED =", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDNotEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_CREATED <>", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDGreaterThan(Date value) {
            addCriterionForJDBCDate("DATE_CREATED >", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_CREATED >=", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDLessThan(Date value) {
            addCriterionForJDBCDate("DATE_CREATED <", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DATE_CREATED <=", value, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_CREATED in", values, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDNotIn(List<Date> values) {
            addCriterionForJDBCDate("DATE_CREATED not in", values, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_CREATED between", value1, value2, "DATE_CREATED");
            return this;
        }

        public Criteria andDATE_CREATEDNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DATE_CREATED not between", value1, value2, "DATE_CREATED");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIsNull() {
            addCriterion("VIDEO_STATUS_ID is null");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIsNotNull() {
            addCriterion("VIDEO_STATUS_ID is not null");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID =", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <>", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDGreaterThan(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID >", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID >=", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDLessThan(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VIDEO_STATUS_ID <=", value, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDIn(List<BigDecimal> values) {
            addCriterion("VIDEO_STATUS_ID in", values, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotIn(List<BigDecimal> values) {
            addCriterion("VIDEO_STATUS_ID not in", values, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_STATUS_ID between", value1, value2, "VIDEO_STATUS_ID");
            return this;
        }

        public Criteria andVIDEO_STATUS_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VIDEO_STATUS_ID not between", value1, value2, "VIDEO_STATUS_ID");
            return this;
        }
    }
}