package com.busterblocks.rental.persistence.table.dao;

import com.busterblocks.rental.persistence.table.dto.VideoRentalDto;
import com.busterblocks.rental.persistence.table.dto.VideoRentalDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface VideoRentalDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int countByExample(VideoRentalDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByExample(VideoRentalDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal VIDEO_RENTAL_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insert(VideoRentalDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insertSelective(VideoRentalDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    List<VideoRentalDto> selectByExample(VideoRentalDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    VideoRentalDto selectByPrimaryKey(BigDecimal VIDEO_RENTAL_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExampleSelective(VideoRentalDto record, VideoRentalDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExample(VideoRentalDto record, VideoRentalDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKeySelective(VideoRentalDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.VIDEO_RENTAL
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKey(VideoRentalDto record);
}