package com.busterblocks.customer.persistence.table.dao;

import com.busterblocks.customer.persistence.table.dto.CustomerDto;
import com.busterblocks.customer.persistence.table.dto.CustomerDtoExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CustomerDtoDAOImpl extends SqlMapClientDaoSupport implements CustomerDtoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public CustomerDtoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int countByExample(CustomerDtoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("HR_CUSTOMER.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByExample(CustomerDtoExample example) {
        int rows = getSqlMapClientTemplate().delete("HR_CUSTOMER.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int deleteByPrimaryKey(BigDecimal CUSTOMER_ID) {
        CustomerDto key = new CustomerDto();
        key.setCUSTOMER_ID(CUSTOMER_ID);
        int rows = getSqlMapClientTemplate().delete("HR_CUSTOMER.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insert(CustomerDto record) {
        getSqlMapClientTemplate().insert("HR_CUSTOMER.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void insertSelective(CustomerDto record) {
        getSqlMapClientTemplate().insert("HR_CUSTOMER.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    @SuppressWarnings("unchecked")
    public List<CustomerDto> selectByExample(CustomerDtoExample example) {
        List<CustomerDto> list = getSqlMapClientTemplate().queryForList("HR_CUSTOMER.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public CustomerDto selectByPrimaryKey(BigDecimal CUSTOMER_ID) {
        CustomerDto key = new CustomerDto();
        key.setCUSTOMER_ID(CUSTOMER_ID);
        CustomerDto record = (CustomerDto) getSqlMapClientTemplate().queryForObject("HR_CUSTOMER.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExampleSelective(CustomerDto record, CustomerDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_CUSTOMER.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByExample(CustomerDto record, CustomerDtoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("HR_CUSTOMER.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKeySelective(CustomerDto record) {
        int rows = getSqlMapClientTemplate().update("HR_CUSTOMER.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public int updateByPrimaryKey(CustomerDto record) {
        int rows = getSqlMapClientTemplate().update("HR_CUSTOMER.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private static class UpdateByExampleParms extends CustomerDtoExample {
        private Object record;

        public UpdateByExampleParms(Object record, CustomerDtoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}