package com.busterblocks.customer.persistence.table.dao;

import com.busterblocks.customer.persistence.table.dto.CustomerDto;
import com.busterblocks.customer.persistence.table.dto.CustomerDtoExample;
import java.math.BigDecimal;
import java.util.List;

public interface CustomerDtoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int countByExample(CustomerDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByExample(CustomerDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int deleteByPrimaryKey(BigDecimal CUSTOMER_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insert(CustomerDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    void insertSelective(CustomerDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    List<CustomerDto> selectByExample(CustomerDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    CustomerDto selectByPrimaryKey(BigDecimal CUSTOMER_ID);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExampleSelective(CustomerDto record, CustomerDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByExample(CustomerDto record, CustomerDtoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKeySelective(CustomerDto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    int updateByPrimaryKey(CustomerDto record);
}