package com.busterblocks.customer.persistence.table.dto;

import java.math.BigDecimal;

public class CustomerDto {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.CUSTOMER.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private BigDecimal CUSTOMER_ID;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.CUSTOMER.FIRST_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String FIRST_NAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.CUSTOMER.SURNAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String SURNAME;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.CUSTOMER.CONTACT_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String CONTACT_NUMBER;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column HR.CUSTOMER.ID_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    private String ID_NUMBER;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.CUSTOMER.CUSTOMER_ID
     *
     * @return the value of HR.CUSTOMER.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public BigDecimal getCUSTOMER_ID() {
        return CUSTOMER_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.CUSTOMER.CUSTOMER_ID
     *
     * @param CUSTOMER_ID the value for HR.CUSTOMER.CUSTOMER_ID
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setCUSTOMER_ID(BigDecimal CUSTOMER_ID) {
        this.CUSTOMER_ID = CUSTOMER_ID;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.CUSTOMER.FIRST_NAME
     *
     * @return the value of HR.CUSTOMER.FIRST_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getFIRST_NAME() {
        return FIRST_NAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.CUSTOMER.FIRST_NAME
     *
     * @param FIRST_NAME the value for HR.CUSTOMER.FIRST_NAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setFIRST_NAME(String FIRST_NAME) {
        this.FIRST_NAME = FIRST_NAME == null ? null : FIRST_NAME.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.CUSTOMER.SURNAME
     *
     * @return the value of HR.CUSTOMER.SURNAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getSURNAME() {
        return SURNAME;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.CUSTOMER.SURNAME
     *
     * @param SURNAME the value for HR.CUSTOMER.SURNAME
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setSURNAME(String SURNAME) {
        this.SURNAME = SURNAME == null ? null : SURNAME.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.CUSTOMER.CONTACT_NUMBER
     *
     * @return the value of HR.CUSTOMER.CONTACT_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getCONTACT_NUMBER() {
        return CONTACT_NUMBER;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.CUSTOMER.CONTACT_NUMBER
     *
     * @param CONTACT_NUMBER the value for HR.CUSTOMER.CONTACT_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setCONTACT_NUMBER(String CONTACT_NUMBER) {
        this.CONTACT_NUMBER = CONTACT_NUMBER == null ? null : CONTACT_NUMBER.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column HR.CUSTOMER.ID_NUMBER
     *
     * @return the value of HR.CUSTOMER.ID_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getID_NUMBER() {
        return ID_NUMBER;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column HR.CUSTOMER.ID_NUMBER
     *
     * @param ID_NUMBER the value for HR.CUSTOMER.ID_NUMBER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setID_NUMBER(String ID_NUMBER) {
        this.ID_NUMBER = ID_NUMBER == null ? null : ID_NUMBER.trim();
    }
}