package com.busterblocks.customer.persistence.table.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CustomerDtoExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public CustomerDtoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected CustomerDtoExample(CustomerDtoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table HR.CUSTOMER
     *
     * @ibatorgenerated Mon Jun 15 13:29:27 CAT 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCUSTOMER_IDIsNull() {
            addCriterion("CUSTOMER_ID is null");
            return this;
        }

        public Criteria andCUSTOMER_IDIsNotNull() {
            addCriterion("CUSTOMER_ID is not null");
            return this;
        }

        public Criteria andCUSTOMER_IDEqualTo(BigDecimal value) {
            addCriterion("CUSTOMER_ID =", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDNotEqualTo(BigDecimal value) {
            addCriterion("CUSTOMER_ID <>", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDGreaterThan(BigDecimal value) {
            addCriterion("CUSTOMER_ID >", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CUSTOMER_ID >=", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDLessThan(BigDecimal value) {
            addCriterion("CUSTOMER_ID <", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CUSTOMER_ID <=", value, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDIn(List<BigDecimal> values) {
            addCriterion("CUSTOMER_ID in", values, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDNotIn(List<BigDecimal> values) {
            addCriterion("CUSTOMER_ID not in", values, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUSTOMER_ID between", value1, value2, "CUSTOMER_ID");
            return this;
        }

        public Criteria andCUSTOMER_IDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUSTOMER_ID not between", value1, value2, "CUSTOMER_ID");
            return this;
        }

        public Criteria andFIRST_NAMEIsNull() {
            addCriterion("FIRST_NAME is null");
            return this;
        }

        public Criteria andFIRST_NAMEIsNotNull() {
            addCriterion("FIRST_NAME is not null");
            return this;
        }

        public Criteria andFIRST_NAMEEqualTo(String value) {
            addCriterion("FIRST_NAME =", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMENotEqualTo(String value) {
            addCriterion("FIRST_NAME <>", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMEGreaterThan(String value) {
            addCriterion("FIRST_NAME >", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME >=", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMELessThan(String value) {
            addCriterion("FIRST_NAME <", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMELessThanOrEqualTo(String value) {
            addCriterion("FIRST_NAME <=", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMELike(String value) {
            addCriterion("FIRST_NAME like", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMENotLike(String value) {
            addCriterion("FIRST_NAME not like", value, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMEIn(List<String> values) {
            addCriterion("FIRST_NAME in", values, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMENotIn(List<String> values) {
            addCriterion("FIRST_NAME not in", values, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMEBetween(String value1, String value2) {
            addCriterion("FIRST_NAME between", value1, value2, "FIRST_NAME");
            return this;
        }

        public Criteria andFIRST_NAMENotBetween(String value1, String value2) {
            addCriterion("FIRST_NAME not between", value1, value2, "FIRST_NAME");
            return this;
        }

        public Criteria andSURNAMEIsNull() {
            addCriterion("SURNAME is null");
            return this;
        }

        public Criteria andSURNAMEIsNotNull() {
            addCriterion("SURNAME is not null");
            return this;
        }

        public Criteria andSURNAMEEqualTo(String value) {
            addCriterion("SURNAME =", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMENotEqualTo(String value) {
            addCriterion("SURNAME <>", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMEGreaterThan(String value) {
            addCriterion("SURNAME >", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SURNAME >=", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMELessThan(String value) {
            addCriterion("SURNAME <", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMELessThanOrEqualTo(String value) {
            addCriterion("SURNAME <=", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMELike(String value) {
            addCriterion("SURNAME like", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMENotLike(String value) {
            addCriterion("SURNAME not like", value, "SURNAME");
            return this;
        }

        public Criteria andSURNAMEIn(List<String> values) {
            addCriterion("SURNAME in", values, "SURNAME");
            return this;
        }

        public Criteria andSURNAMENotIn(List<String> values) {
            addCriterion("SURNAME not in", values, "SURNAME");
            return this;
        }

        public Criteria andSURNAMEBetween(String value1, String value2) {
            addCriterion("SURNAME between", value1, value2, "SURNAME");
            return this;
        }

        public Criteria andSURNAMENotBetween(String value1, String value2) {
            addCriterion("SURNAME not between", value1, value2, "SURNAME");
            return this;
        }

        public Criteria andCONTACT_NUMBERIsNull() {
            addCriterion("CONTACT_NUMBER is null");
            return this;
        }

        public Criteria andCONTACT_NUMBERIsNotNull() {
            addCriterion("CONTACT_NUMBER is not null");
            return this;
        }

        public Criteria andCONTACT_NUMBEREqualTo(String value) {
            addCriterion("CONTACT_NUMBER =", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERNotEqualTo(String value) {
            addCriterion("CONTACT_NUMBER <>", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERGreaterThan(String value) {
            addCriterion("CONTACT_NUMBER >", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACT_NUMBER >=", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERLessThan(String value) {
            addCriterion("CONTACT_NUMBER <", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("CONTACT_NUMBER <=", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERLike(String value) {
            addCriterion("CONTACT_NUMBER like", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERNotLike(String value) {
            addCriterion("CONTACT_NUMBER not like", value, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERIn(List<String> values) {
            addCriterion("CONTACT_NUMBER in", values, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERNotIn(List<String> values) {
            addCriterion("CONTACT_NUMBER not in", values, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERBetween(String value1, String value2) {
            addCriterion("CONTACT_NUMBER between", value1, value2, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andCONTACT_NUMBERNotBetween(String value1, String value2) {
            addCriterion("CONTACT_NUMBER not between", value1, value2, "CONTACT_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERIsNull() {
            addCriterion("ID_NUMBER is null");
            return this;
        }

        public Criteria andID_NUMBERIsNotNull() {
            addCriterion("ID_NUMBER is not null");
            return this;
        }

        public Criteria andID_NUMBEREqualTo(String value) {
            addCriterion("ID_NUMBER =", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERNotEqualTo(String value) {
            addCriterion("ID_NUMBER <>", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERGreaterThan(String value) {
            addCriterion("ID_NUMBER >", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER >=", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERLessThan(String value) {
            addCriterion("ID_NUMBER <", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("ID_NUMBER <=", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERLike(String value) {
            addCriterion("ID_NUMBER like", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERNotLike(String value) {
            addCriterion("ID_NUMBER not like", value, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERIn(List<String> values) {
            addCriterion("ID_NUMBER in", values, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERNotIn(List<String> values) {
            addCriterion("ID_NUMBER not in", values, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERBetween(String value1, String value2) {
            addCriterion("ID_NUMBER between", value1, value2, "ID_NUMBER");
            return this;
        }

        public Criteria andID_NUMBERNotBetween(String value1, String value2) {
            addCriterion("ID_NUMBER not between", value1, value2, "ID_NUMBER");
            return this;
        }
    }
}